CUR_DIR = $(shell pwd)

SRC_DIR = $(CUR_DIR)

SRCS := ft_isalpha.c ft_isdigit.c ft_isalnum.c ft_isascii.c \
	ft_isprint.c ft_strlen.c ft_memset.c ft_bzero.c \
	ft_memcpy.c ft_memmove.c ft_strlcpy.c ft_strlcat.c \
	ft_toupper.c ft_tolower.c ft_strchr.c ft_strrchr.c \
	ft_strncmp.c ft_memchr.c ft_memcmp.c ft_strnstr.c \
	ft_atoi.c ft_calloc.c ft_strdup.c ft_substr.c \
	ft_strjoin.c  ft_strtrim.c ft_split.c ft_itoa.c \
	ft_strmapi.c ft_striteri.c ft_putchar_fd.c ft_putstr_fd.c \
	ft_putendl_fd.c ft_putnbr_fd.c

# Lista de arquivos .c para a parte bônus
BONUS_SRCS = ft_lstnew_bonus.c ft_lstadd_front_bonus.c \
             ft_lstsize_bonus.c ft_lstlast_bonus.c ft_lstadd_back_bonus.c \
             ft_lstdelone_bonus.c ft_lstclear_bonus.c ft_lstiter_bonus.c \
             ft_lstmap_bonus.c

OBJ_DIR = $(CUR_DIR)
BONUS_OBJS = $(BONUS_SRCS:.c=.o)

CFILES = $(SRCS:*.c)

OFILES = $(SRCS:.c=.o)

CFLAGS = -Wall -Wextra -Werror

NAME = libft.a

all: $(NAME) clean

bonus: $(OBJS) $(BONUS_OBJS)
	ar rcs $(NAME) $(OBJS) $(BONUS_OBJS)

%.o: %.c libft.h  Makefile
	 $(CC) $(CFLAGS) -c $< -o $@

$(NAME): $(OFILES)
	ar rcs $(NAME) $(OFILES)

clean:
	rm -f $(OFILES)

fclean:clean
	rm -f $(CUR_DIR)/$(NAME)

re:fclean $(NAME)
	rm -f $(OFILES)

.PHONY:
	all clean fclean re bonus
